In [1]:
import cv2

In [6]:
img_grey = cv2.imread("smallgray.png", 0) # 0 - read as greyscale image
print(img_grey)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [5]:
cv2.imwrite("new_small_gray.png", img_grey)

True

In [9]:
img_grey[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [10]:
img_grey.shape

(3L, 5L)

In [11]:
for i in img_grey:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [12]:
for i in img_grey.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [15]:
import numpy
ims = numpy.hstack((img_grey, img_grey))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
imv = numpy.vstack((img_grey, img_grey))
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
lst = numpy.hsplit(ims, 5)
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]